// A CLASS is a blueprint that describes what a Rider looks like
// Every rider in our app will be created from this blueprint
class RiderModel {

  // ═══════════════════════════════
  // FIELDS - the information boxes
  // ═══════════════════════════════

  // final means this value can NEVER change after it is set
  // String means this box holds text only
  final String id;         // unique ID generated by Firebase e.g "xK9mP2qR7"
  final String name;       // rider's full name e.g "Emeka John"
  final String email;      // rider's email e.g "emeka@gmail.com"
  final String phone;      // rider's phone e.g "08012345678"
  
  // String? means nullable - rider may not have a photo yet
  // The ? means this box is allowed to be empty
  final String? profilePhoto;
  
  // bool means only true or false - rider is either online or not
  final bool isOnline;
  
  // double means decimal number - GPS coordinates have decimals
  // e.g latitude: 6.455027  longitude: 3.384082
  final double latitude;
  final double longitude;
  
  // what vehicle the rider uses e.g "bike" or "car"
  final String vehicleType;
  
  // rider's rating out of 5 e.g 4.8
  // double because rating can be a decimal
  final double rating;


  // ═══════════════════════════════════════════════
  // CONSTRUCTOR - instruction for how to create a rider
  // ═══════════════════════════════════════════════

  // RiderModel({...}) is the constructor
  // The {} means these are NAMED parameters
  // You must mention the name when creating a rider e.g name: 'Emeka'
  RiderModel({
    required this.id,           // MUST provide id
    required this.name,         // MUST provide name
    required this.email,        // MUST provide email
    required this.phone,        // MUST provide phone
    this.profilePhoto,          // OPTIONAL - no required because nullable
    required this.isOnline,     // MUST provide online status
    required this.latitude,     // MUST provide GPS latitude
    required this.longitude,    // MUST provide GPS longitude
    required this.vehicleType,  // MUST provide vehicle type
    required this.rating,       // MUST provide rating
  });


  // ═══════════════════════════════════════════════════════
  // toMap - converts Dart object INTO Firebase format
  // ═══════════════════════════════════════════════════════

  // Map<String, dynamic> means key-value pairs like {'name': 'Emeka'}
  // Firebase only understands this format not Dart objects
  // Think of toMap as PACKING your rider into a box to send to Firebase
  Map<String, dynamic> toMap() {
    return {
      'id': id,                       // key: 'id'  value: the actual id
      'name': name,                   // key: 'name' value: the actual name
      'email': email,
      'phone': phone,
      'profilePhoto': profilePhoto,   // will be null if not set
      'isOnline': isOnline,
      'latitude': latitude,
      'longitude': longitude,
      'vehicleType': vehicleType,
      'rating': rating,
    };
  }


  // ═══════════════════════════════════════════════════════════
  // factory fromMap - converts Firebase data INTO Dart object
  // ═══════════════════════════════════════════════════════════

  // factory means this is a special constructor for creating
  // an object FROM existing data (the Firebase map)
  // Think of fromMap as UNPACKING the box Firebase sent back to you
  // map['id'] means go into the map and find the value with key 'id'
  factory RiderModel.fromMap(Map<String, dynamic> map) {
    return RiderModel(
      id: map['id'],                    // get 'id' from Firebase map
      name: map['name'],                // get 'name' from Firebase map
      email: map['email'],
      phone: map['phone'],
      profilePhoto: map['profilePhoto'], // will be null if rider has no photo
      isOnline: map['isOnline'],
      latitude: map['latitude'],
      longitude: map['longitude'],
      vehicleType: map['vehicleType'],
      rating: map['rating'],
    );
  }
}


// ═══════════════════════════
// HOW TO CREATE A RIDER OBJECT
// ═══════════════════════════

void main() {
  // Creating a real rider object from the RiderModel blueprint
  // This is called INSTANTIATION - creating an instance of a class
  RiderModel rider1 = RiderModel(
    id: 'xK9mP2qR7',
    name: 'Emeka John',
    email: 'emeka@gmail.com',
    phone: '08012345678',
    profilePhoto: null,     // no photo yet
    isOnline: true,
    latitude: 6.455027,
    longitude: 3.384082,
    vehicleType: 'bike',
    rating: 4.8,
  );

  // Accessing fields using dot notation
  // dot (.) means go inside the object and get this field
  print('Name: ${rider1.name}');
  print('Online: ${rider1.isOnline}');
  print('Rating: ${rider1.rating}');
  print('Vehicle: ${rider1.vehicleType}');
  print('Photo: ${rider1.profilePhoto}'); // prints null
}